### ISSUE TITLE
Enable python bindings by default

### ISSUE THREAD

**Issue by nim65s** [stonneau/spline#123]
Hi, 

I think we should consider reverting #88.

The default behavior of this package is opposite of everything else we have, and I was just able to make a broken v1.4.0 release because of it.

@pFernbach @MaximilienNaveau : do you have news about that ferrum issue with those bindings ?

I think if you really need to keep this change, this change should be local to your packaging, so you could have a patch for this in your package manager.

**Comment by MaximilienNaveau** [comment]
Yes let's revert that!
I will make a proper fork in the gitlab of PAL with a ferrum branch.
Don't worry.
